### ISSUE TITLE
Implement `onboarding` flow

### ISSUE THREAD

**Issue by 50-Course** [SafeBuddy-Fintech23/SafeBuddy#8]
Onboarding is a great tool to tell users about our app. We should make them comfortable enough about using our app.

<img src="https://i.giphy.com/media/9M53jrUZHQuq3ovY9P/giphy.webp" data-canonical-src="https://i.giphy.com/media/huyZxIJvtqVeRp7QcS/giphy.webp" width="200" height="250" />

## Acceptance Criteria

- [ ] Convert design into code, creating a seamless experience

#### *We are trusting you on this one* 🤓

**Comment by SamuelWakoli** [comment]
I have implemented it at the *dev* branch. Still working on more content to make it look cool

**Comment by jayteealao** [comment]
Reopened this issue, to drop some comments will come back and close it later.
Well done, I'll like to build and run this flow myself before closing the issue

**Comment by 50-Course** [comment]
Gotta fix the CI @SamuelWakoli , lets have our call tonight
